# Funding configuration for jaypatel208

# GitHub Sponsors
github: [jaypatel208]

# Buy Me A Coffee
buy_me_a_coffee: jaypatel208

# Custom URLs for additional payment methods
custom: ["upi://pay?pa=technoguys037493@okaxis&pn=Jay%20Patel"]